server:
  port: 9000
spring:
  application:
   name: ad-gateway
eureka:
  client:
    service-url:
      defaultZone: http://server1:8000/eureka/,http://server1:8001/eureka/,http://server1:8002/eureka/
zuul:
  prefix: /immoc
  routes:
    sponsor:
      path: /ad-sponsor
      serviceId: eureka-client-ad-sponsor
      strip-prefix: false